---
ID: "4a5c42db-5e33-4383-816b-7189d634af7f"
Parent: "257698ea-ca47-4496-ac8e-cfb125ed802d"
Template: "3a45a723-64ee-4919-9d41-02fd40fd1466"
Path: /sitecore/layout/Layouts/Project/Agency/Default
DB: master
SharedFields:
- ID: "a036b2bc-ba04-44f6-a75f-bae6cd242abf"
  Hint: Path
  Value: /Views/Website/Layouts/Default.cshtml
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180109T182412Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
